### ISSUE TITLE
Wrong URL on slide 72

### ISSUE THREAD

**Issue by LudovicRousseau** [franton/2017-SC-Talk#1]
On page 72 the URL https://ludovicorousseau.blogspot.com/2015/02/debug-smart-card-application-on-yosemite.html is wrong.
It should be https://ludovicrousseau.blogspot.fr/2015/02/debug-smart-card-application-on-yosemite.html (there is an extra "o" between "ludovic" and "rousseau").

**Comment by franton** [comment]
Corrections made and new slides uploaded.
